// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class Authors
{
    public int AuthorId { get; set; }

    public string Firstname { get; set; }

    public string Efternamn { get; set; }

    public DateTime? Created { get; set; }

    public virtual ICollection<Books> Books { get; } = new List<Books>();
}