// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class Books
{
    public int BookId { get; set; }

    public int? UserId { get; set; }

    public int? AuthorId { get; set; }

    public int? GenreId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Isbn { get; set; }

    public string Imagepath { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? Created { get; set; }

    public virtual Authors Author { get; set; }

    public virtual Genres Genre { get; set; }

    public virtual ICollection<Reviews> Reviews { get; } = new List<Reviews>();

    public virtual Users User { get; set; }
}