// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class Genres
{
    public int GenreId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Books> Books { get; } = new List<Books>();
}