// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class Users
{
    public int UserId { get; set; }

    public int? UserinfoId { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public virtual ICollection<Books> Books { get; } = new List<Books>();

    public virtual ICollection<Reviews> Reviews { get; } = new List<Reviews>();

    public virtual Userinfo Userinfo { get; set; }
}